import Header from '@/components/Header';
import Head from 'next/head';
import Image from 'next/image';
import { SearchIcon, MicrophoneIcon } from '@heroicons/react/solid';

export default function Home() {
  return (
    <>
      <Head>
        <title>Google clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header*/}
      <Header />
      {/*Body*/}
      <form className="flex flex-col items-center mt-40">
        <Image
          width="300"
          height="100"
          src="https://free-png.ru/wp-content/uploads/2020/11/21-215328_-google-png-animated-logos-f94db687.png"
          alt="google"
        />
        <div className="flex items-center p-2 mt-5 hover:shadow-inner justify-between rounded-full w-full py-3 px-5 mx-auto max-w-[90%] sm:max-w-xl border border-gray-200">
          <SearchIcon className="h-5 text-gray-500 mr-2 " />
          <input className="w-[93%] outline-0 " type="text" />
          <MicrophoneIcon className="h-5" />
        </div>

        <div className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
          <button className="btn">Google Search</button>
          <button className="btn">I'm Feeling Lucky</button>
        </div>
      </form>

      {/*Footer*/}
    </>
  );
}
